config/routes.rb
Rails.application.routes.draw do
  root to: 'users#show'

  get '/main', to: 'static_pages#main'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  delete '/delete_multiple_tasks', to: 'tasks#delete_multiple'
  put '/complete_multiple_tasks', to: 'tasks#complete_uncomplete_multiple'

  resources :users do
    resources :tasks
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    default_scope -> { order(priority: :desc) }
    validates :title, presence: true, length: { maximum: 255 }
    validates :priority, presence: true, 
                        numericality: { only_integer: true },
                        inclusion: 0..10
    validates :due_date, presence: true
    validates :user_id, presence: true
    validate :due_date_cant_be_in_past

    private
        def due_date_cant_be_in_past
            if !!due_date && due_date < DateTime.now
                errors.add(:due_date, "can't be in past")
            end
        end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :logged_in_user
    before_action :correct_user

    def show
        @user = User.find(params[:user_id])
        @task = @user.tasks.find(params[:id])
    end

    def edit
        @user = User.find(params[:user_id])
        @task = @user.tasks.find(params[:id])
    end

    def new
        @user = current_user
        @task = Task.new
    end

    def create
        @user = current_user
        @task = current_user.tasks.build(task_params)
        if @task.save
            flash[:success] = "Task has been created!"
            redirect_to root_url
        else
            render 'new'
        end
    end

    def update
        @user = User.find(params[:user_id])
        @task = Task.find(params[:id])
        if @task.update_attributes(task_params)
            flash[:success] = "Task updated!"
            redirect_to root_url
        else
            render 'edit'
        end
    end

    def destroy
        task = current_user.tasks.find_by(id: params[:id])
        task.destroy
        
        respond_to do |format|
            format.html do 
                flash[:success] = "Task was deleted!"
                redirect_to root_url
            end
            format.js { render :json => { :taskId => params[:id] }, callback: 'deleteTask' }
        end
    end

    def delete_multiple
        user = User.find(params[:user_id])
        ids = params[:ids]
        user.tasks.where(id: ids).destroy_all
        respond_to do |format|
            format.js { render :json => { :ids => ids }, callback: 'batchDelete' }
        end
    end

    def complete_uncomplete_multiple
        user = User.find(params[:user_id])
        ids = params[:ids]
        state = params[:complete] == "true" ? false : true
        user.tasks.where(id: ids).update_all(active: state)
        respond_to do |format|
            format.js { render :json => { :ids => ids, :state => state }, callback: 'moveToCompleted' }
        end
    end

    private

        def task_params
            params.require(:task).permit(:title, :priority, :due_date, :description)
        end

        # Confirms a logged in user
        def logged_in_user
            unless logged_in?
                store_location
                flash[:danger] = "Please Log In!"
                redirect_to login_url
            end
        end

        # Confirms the correct user
        def correct_user
            user = User.find(params[:user_id])
            unless current_user?(user)
                flash[:danger] = "You are not allowed to view, modify or destroy another users task!"
                redirect_to root_url 
            end
        end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.html.erb
<tr id="task-<%= task.id %>" class="task_row">
  <td class="active_checkbox">
    <input type="checkbox" name="active" id="checkbox-<%= task.id %>">
  </td>
  <td class="title"><%= link_to task.title, user_task_path(@user.id, task.id) %></td>
  <td class="due_date"><%= task.due_date.strftime("%F") %></td>
  <td class="priority"><%= task.priority %></td>
  <td class="edit_task"><%= button_to "Edit", edit_user_task_path(@user.id, task.id), method: :get, class: "btn btn-warning buttons" %></td>
  <td class="delete_task"><%= button_to "Delete", user_task_path(@user.id, task.id), method: :delete, class: "btn btn-danger buttons", data: { confirm: "Are you sure?" }, remote: true %></td>
</tr>

app/views/tasks/edit.html.erb
<% provide(:title, 'Edit Task') %>
<h1>Edit Task</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@task, url: user_task_path(@user.id, @task.id), method: :put) do |f| %>
      <%= render 'shared/task_error_messages' %>
      <ul class="errors_js"></ul>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :priority %>
      <%= f.number_field :priority, in: 0..10, step: 1, class: 'form-control' %>

      <%= f.label :due_date %>
      <%= f.text_field :due_date, class: 'datepicker form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, size: "24x6", class: 'form-control' %>


      <%= f.submit "Update task", class: "btn btn-primary", data: {disable_with: false}%>
    <% end %>

  </div>
</div>

<script>
  $(document).ready(function(){
    var val = $(".datepicker").val();
    var date = new Date(val)
    $(".datepicker").datepicker("update", date)
  });
</script>

app/views/tasks/new.html.erb
<% provide(:title, 'Create Task') %>
<h1>Create New Task</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@task, url: user_tasks_path(@user.id)) do |f| %>
      <%= render 'shared/task_error_messages' %>
      <ul class="errors_js"></ul>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :priority %>
      <%= f.number_field :priority, in: 0..10, step: 1, class: 'form-control' %>
      
      <%= f.label :due_date %>
      <%= f.text_field :due_date, class: 'datepicker form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, size: "24x6", class: 'form-control' %>


      <%= f.submit "Create task", class: "btn btn-primary", data: {disable_with: false} %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, @task.title) %>
<div class="task_show_block">
    <div class="row info_row">
        <div class="col-md-3 col-md-offset-1">
            <strong>Title</strong>: <%= @task.title %>
        </div>
        <div class="col-md-2">
            <strong>Due date</strong>: <%= @task.due_date.to_date %>
        </div>
        <div class="col-md-2">
            <strong>Updated</strong>: <%= @task.updated_at.to_date %>
        </div>
        <div class= "col-md-2">
            <strong>Priority</strong>: <%= @task.priority %>
        </div>
        <div class="col-md-2">
            <strong>Active</strong>: <%= @task.active %>
        </div>
    </div>
    <div class="row description_row">
        <div class="col-md-8 col-md-offset-3">
            <strong>Description</strong>: <%= @task.description %>
        </div>
    </div>
</div>
<div class="row edit_button_row">
    <div class="col-md-2 col-md-offset-3">
        <%= button_to "Back to tasks", user_path(@user.id), method: :get, class: "btn btn-primary" %>
    </div>
    
    <div class="col-md-2">
        <%= button_to "Edit task", edit_user_task_path(@user.id, @task.id), method: :get, class: "btn btn-warning" %>
    </div>

    <div class="col-md-2">
        <%= button_to "Delete task", user_task_path(@user.id, @task.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
    </div>
</div>