config/routes.rb
Rails.application.routes.draw do
  root to: 'users#show'

  get '/main', to: 'static_pages#main'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  delete '/delete_multiple_tasks', to: 'tasks#delete_multiple'
  put '/complete_multiple_tasks', to: 'tasks#complete_uncomplete_multiple'

  resources :users do
    resources :tasks
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token, :activation_token, :reset_token
    has_many :tasks, dependent: :destroy
    before_save :downcase_email
    before_create :create_activation_digest

    validates :first_name, presence: true, length: { maximum: 50 }
    validates :last_name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    def full_name
        return "#{self.first_name} #{self.last_name}"
    end

    # returns the hash digest of the given string
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = self.send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end

    # Sets the password reset attributes.
    def create_reset_digest
        self.reset_token = User.new_token
        update_columns( reset_digest: User.digest(reset_token),
                        reset_sent_at: Time.zone.now )
    end

    # Sends password reset email.
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    private

        def downcase_email
            self.email = email.downcase
        end

        def create_activation_digest
            self.activation_token = User.new_token
            self.activation_digest = User.digest(activation_token)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:edit, :update, :destroy, :show]
    before_action :show_page_as_root, only: [:show]
    before_action :correct_user, only: [:edit, :update, :show]
    before_action :admin_user, only: :destroy

    def index
        @users = User.paginate(page: params[:page])
    end

    def show
        @user = User.find(params[:id])
        @active_tasks = @user.tasks.where(active: true)
        @finished_tasks = @user.tasks.where(active: false)
        @tasks = @user.tasks
    end

    def create
        @user = User.create(user_params)
        if @user.save
            UserMailer.account_activation(@user).deliver_now
            flash[:success] = "Please check your email to activate your account"
            redirect_to main_path
        else
            render 'new'
        end
    end

    def new
        @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            flash[:success] = "Profile updated"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
        User.find(params[:id]).destroy
        flash[:success] = "User deleted!"
        redirect_to users_url
    end

    private 

        # Permits only specified fields
        def user_params
            params.require(:user).permit(:first_name, :last_name, 
                                        :email, :password, :password_confirmation)
        end
   
        # Confirms a logged in user
        def logged_in_user
            unless logged_in?
                store_location
                flash[:danger] = "Please Log In!"
                redirect_to login_url
            end
        end

        # Confirms the correct user
        def correct_user
            @user = User.find_by(id: params[:id])
            redirect_to root_url unless current_user?(@user)
        end

        # Confirms an admin
        def admin_user
            redirect_to(root_url) unless current_user.admin?
        end

        # If show action used from root route set params[:id] as session[:user_id]
        def show_page_as_root
            if !params[:id]
                params[:id] = session[:user_id]
            end
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit #{@user.first_name} #{@user.last_name}") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <ul class="errors_js"></ul>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary", data: {disable_with: false} %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to "#{user.first_name} #{user.last_name}", user %>
        <% if !current_user.nil? && current_user.admin? && !current_user?(user) %>
        | <%= link_to "Delete", user, method: :delete,
                                      data: { confirm: "You sure?" } %>
        <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row sign_up">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <ul class="errors_js"></ul>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create account", class: "btn btn-primary", data: {disable_with: false} %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.full_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1 class="info_user_id" id="<%= @user.id %>">
        <%= @user.full_name %>
      </h1>
      <p>Today is: <span class="dateline"><%= DateTime.now.to_date %></span></p>
      <%= button_to "Create New Task", new_user_task_path(@user.id), class: "btn btn-primary", method: :get %>
    </section>
  </aside>
  <div class="col-md-8">
    <ul class="nav nav-tabs">
      <li class="active">
        <a data-toggle="tab" href="#active_tasks_container">Active tasks</a>
      </li>
      <li>
        <a data-toggle="tab" href="#finished_tasks_container">Finished tasks</a>
      </li>
    </ul>
    
    <div class="tab-content">
    
    <div class="tab-pane fade in active" id="active_tasks_container">
        <% if @active_tasks.any? %>
          <h3>Number of active tasks: <span id="active-count"><%= @active_tasks.count %></span></h3>
        <% else %>
          <h3>You have no active task! Create one!</h3>
        <% end %>
        <div class="select_buttons">
          <button class="btn btn-default" id="check_all_active">Check all</button>
          <button class="btn btn-default" id="uncheck_all_active">Uncheck all</button>
          <button class="btn btn-success" id="complete_tasks">Mark completed</button>
          <button class="btn btn-danger" id="delete_selected_active_tasks">Delete Selected</button>  
        </div>
        <table class="table-striped table-hover table-active-tasks table-tasks">
          <tr class="table_head">
            <th class="col-md-1 text-center checkbox_column"></th>
            <th class="col-md-2 text-center title_column">Title</th>
            <th class="col-md-2 text-center due_date_column">Due Date</th>
            <th class="col-md-1 text-center priority_column">Priority</th>
            <th class="col-md-1 text-center edit_task_column"></th>
            <th class="col-md-1 text-center delete_task_column"></th>
          </tr>
      <% if @active_tasks.any? %>
          <%= render partial: 'tasks/task', collection: @active_tasks, as: :task %>
      <% end %>
        </table>
    </div>

    <div class="tab-pane fade" id="finished_tasks_container">
    <% if @finished_tasks.any? %>
      <h3>Number of finsihed tasks: <span id="finished-count"><%= @finished_tasks.count %></span></h3>
    <% else %>
      <h3>You have no finished task!</h3>
    <% end %>     
      <div class="select_buttons">
        <button class="btn btn-default" id="check_all_finished">Check all</button>
        <button class="btn btn-default" id="uncheck_all_finished">Uncheck all</button>
        <button class="btn btn-warning" id="uncomplete_tasks">Uncomplete</button>
        <button class="btn btn-danger" id="delete_selected_finished_tasks">Delete Selected</button>      
      </div>
      <table class="table-striped table-hover table-finished-tasks table-tasks">
        <tr class="table_head">
          <th class="col-md-1 text-center checkbox_column"></th>
          <th class="col-md-3 text-center title_column">Title</th>
          <th class="col-md-2 text-center due_date_column">Due Date</th>
          <th class="col-md-1 text-center priority_column">Priority</th>
          <th class="col-md-1 text-center edit_task_column"></th>
          <th class="col-md-1 text-center delete_task_column"></th>
        </tr>
    <% if @finished_tasks.any? %>
        <%= render partial: 'tasks/task', collection: @finished_tasks, as: :task %>
    <% end %>
      </table>
    </div>

    </div>

  </div>
</div>